language: bash

sudo: false

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

script:
 - shellcheck $(find . -name '*.sh') bin/*
 - bash tests/test.sh

matrix:
  fast_finish: true
